[BH-1121] Alarm Activation Message
mudita/MuditaOS pull request #3117
Opened 2021-10-29 09:22 UTC by tomaszrybarski-digica

Alarm Activation Message: "&" is replaced with "i" for polish translation

2021-11-22 08:01 UTC, mjan-dev requested changes
Please change base branch to release/1.0.0-bell.

2021-11-22 09:20 UTC, tomaszrybarski-digica commented
> Please change base branch to release/1.0.0-bell.
Changed

2021-11-22 14:27 UTC, mjan-dev approved these changes

2021-11-23 11:55 UTC, paweljonskim approved these changes

2021-11-23 14:38 UTC, swichu91 approved these changes

2021-11-25 15:03 UTC, merged