[BH-1218] fix ui font size
mudita/MuditaOS pull request #3284
Opened 2021-11-22 08:36 UTC by tigransoghbatyan-digica

Set BellSideListItem font sizez according to the design

2021-11-22 08:51 UTC, mjan-dev requested changes
Please switch base branch to release/1.0.0-bell.

2021-11-24 07:52 UTC, tigransoghbatyan-digica commented
> Please switch base branch to release/1.0.0-bell.

done

2021-11-25 13:30 UTC, mjan-dev approved these changes

2021-11-29 17:10 UTC, mjan-dev reviewed
Please switch base to stable now ;)

2021-11-30 12:54 UTC, tomaszrybarski-digica approved these changes

2021-12-07 13:04 UTC, merged