[BH-1251] Fix meditation app respawning
mudita/MuditaOS pull request #3316
Opened 2021-11-24 08:50 UTC by tigransoghbatyan-digica

Prevent meditation app from spawning multiple instances

2021-11-24 09:31 UTC, swichu91 approved these changes

2021-11-24 10:13 UTC, tomaszrybarski-digica approved these changes

2021-11-24 10:13 UTC, paweljonskim approved these changes

2021-11-24 11:10 UTC, mjan-dev requested changes
Blocking until new branch for patch 0 will be created.

2021-11-30 15:56 UTC, mjan-dev reviewed
Please switch to stable ! :)

2021-12-01 07:58 UTC, wojtekrzepecki approved these changes

2021-12-03 15:29 UTC, mjan-dev approved these changes

2021-12-07 13:44 UTC, merged