[BH-1244] Align Alarm Set Window
mudita/MuditaOS pull request #3317
Opened 2021-11-24 09:51 UTC by tomaszrybarski-digica

Proper formatting applied to Alarm Set icon

2021-11-24 10:14 UTC, paweljonskim approved these changes

2021-11-24 11:08 UTC, mjan-dev approved these changes
Blocking as this change is not required for release.

2021-11-24 11:10 UTC, mjan-dev requested changes
Blocking until new branch for patch 0 will be created. It is not of highest priority.

2021-11-25 13:30 UTC, mjan-dev approved these changes

2021-11-25 13:32 UTC, mjan-dev requested changes
Still blocking. Approved by mistake

2021-11-29 17:09 UTC, mjan-dev approved these changes

2021-12-01 09:40 UTC, merged