[BH-1316] Vertical layouts
mudita/MuditaOS pull request #3630
Opened 2022-03-04 16:22 UTC by paweljonskim

Add 2 vertical layouts

2022-03-08 07:50 UTC, pholat requested changes
1. please do not add bell specyfic layouts to app-common
2. please remove TODO we have an issue tracker for such things
3. please try to use MVP we have layouts that tell what the model does...

2022-03-08 08:35 UTC, swichu91 reviewed
Please check the comments. I also tested it locally on Linux build. It seems to be working. Alas, it seems no one thought what should happen when a user sets 24h time format and layout showing AM/PM. Apart from that, I see it is time to incorporate some unit tests into `StateController.cpp`. Let's address this issue in the next PR.

2022-03-15 13:41 UTC, pholat commented on module-apps/apps-common/widgets/TimeSetSpinnerVertical.hpp
> +        TimeSetSpinnerVertical(
this class by design is combining view and model please at least move it to bell specific layouts :bow:

2022-03-16 12:57 UTC, swichu91 commented
> I'd love to continue with the review process, but unfortunately, the home screen seems to be not working on the simulator. It only shows a blank screen without any content. I did a clean rebuild and created a disk image. Can anyone confirm this?

Setting the layout explicitly under the 'Clock face' settings seems to fix the issue. @paweljonskim Is this the correct behavior? 

Apart from that, I was able to use am/pm layout when using 24h format. To trigger it, please follow the steps below:
1. Set time format to 12h.
2. Set any am/pm layout.
3. Switch to 24 time format.
I believe this is something that needs to be addressed.

2022-03-16 13:14 UTC, swichu91 commented on products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutVertical.cpp
> +    {}
It would be better to add a default implementation to the interface. If specific layout don't need specific method, then it can rely on default one.

2022-03-16 13:16 UTC, swichu91 commented on products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutVertical.cpp
> +    void HomeScreenLayoutVertical::setBatteryLevelState(const Store::Battery &batteryContext)
Implementation here is identical with the `HomeScreenLayoutClassic::setBatteryLevelState`. The same goes for many other methods, `isBatteryVisibilityAllowed`

2022-03-16 13:17 UTC, swichu91 commented on products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutVertical.cpp
> +    {}
Please check, https://github.com/mudita/MuditaOS/pull/3630/files#r827994640

2022-03-16 13:17 UTC, swichu91 commented on products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutVertical.cpp
> +    {}
Please check, https://github.com/mudita/MuditaOS/pull/3630/files#r827994640

2022-03-22 06:43 UTC, pholat approved these changes

2022-03-22 07:26 UTC, swichu91 approved these changes

2022-03-22 12:12 UTC, merged