NOISSUE: typo fix
mudita/MuditaOS pull request #3967
Opened 2022-07-13 20:37 UTC by marziel

**Description**

Fixed typos regarding incoming calls. Thus, searching code isn't hindered by those typos anymore.

Make sure that this PR:
- [x] Complies with our guidelines for contributions
- [x] Has unit tests if possible.
- [x] Has documentation updated

2022-07-14 07:53 UTC, pawel-mudita approved these changes

2022-07-14 08:27 UTC, swichu91 requested changes
Please create corresponding JIRA ticket and replace "NOISSUE" with the correct number taken from the ticket.

2022-07-14 08:40 UTC, marziel commented
> Please create corresponding PR and replace "NOISSUE" with the correct PR number.
You mean a Jira ticket (not a PR)? This is the PR

2022-07-15 11:48 UTC, swichu91 commented
> > Please create corresponding PR and replace "NOISSUE" with the correct PR number.
> 
> You mean a Jira ticket (not a PR)? This is the PR

Yep, I meant JIRA ticket. Fixed :)

2022-07-19 10:10 UTC, SP2FET approved these changes

2022-07-20 16:45 UTC, closed without merging