[MOS-884] Importing contacts from SIM card more than once
mudita/MuditaOS pull request #4307
Opened 2023-01-31 18:20 UTC by lukasmas

Fix for importing and removing contacts from SIM card causes issue that imported contacts didn't have a name and could by multiplied.

**Your checklist for this pull request**

Make sure that this PR:
- [x] Complies with our guidelines for contributions
- [ ] Has unit tests if possible
- [ ] Has documentation updated
- [x] Has changelog entry added

2023-01-31 18:48 UTC, marziel requested changes

2023-01-31 18:48 UTC, marziel commented on pure_changelog.md
> +* Fixed for unexpected behavior when removing and importing contacts from SIM card more than once
Instead of just _unexpected behavior_, please briefly write what was the problem (this one is the reason why I "requested changes" on this PR)

2023-01-31 18:48 UTC, marziel commented on module-db/Interface/ContactRecord.cpp
> +    if (matchedNumber.has_value()) {
[minor]
You could invert the condition to `return` earlier making the code less indented and thus more readable

2023-01-31 18:48 UTC, marziel commented on module-db/Interface/ContactRecord.cpp
> +        if (contact.has_value()) {
[minor]
You could incorporate the line above into the `if` as its precondition

2023-02-01 09:43 UTC, marziel commented on module-db/Interface/ContactRecord.cpp
> +    if (not contact.has_value()) {
[minor]
Could be even:
`return contact.has_value() && contact->isTemporary();`

2023-02-01 09:43 UTC, marziel approved these changes

2023-02-03 08:25 UTC, Maciej-Mudita approved these changes

2023-02-03 08:57 UTC, merged