[BH-1720] choose GDB binary based on python version
mudita/MuditaOS pull request #4543
Opened 2023-07-14 15:05 UTC by MateuszSz-mudita

In this version of the run.sh script, the arm-none-eabi-gdb version will be chosen based on its python support and the user will be notified if their version supports python 3 or not.

**Your checklist for this pull request**

Make sure that this PR:
- [X] Complies with our guidelines for contributions
- [ ] Has unit tests if possible
- [ ] Has documentation updated
- [ ] Has changelog entry added

2023-07-18 09:07 UTC, Maciej-Mudita approved these changes

2023-07-18 10:30 UTC, exeosdev requested changes

2023-07-19 08:45 UTC, MateuszSz-mudita commented on run.sh
> +if [ -z ${GDB_ARM+x} ]; then # if GDB_ARM unset, check which GDB binaries are present and choose one
This is already implemented in the next part of the script. First, the script gets all the compatible GDB versions and the python versions they support. Then if possible it chooses a binary with python 3 support. If no such binary is found, it chooses a binary with python 2 support and lastly, if no binaries with python support are found, it chooses the default arm-none-eabi-gdb binary.

2023-07-20 08:26 UTC, exeosdev approved these changes

2023-07-21 08:39 UTC, merged